# Generated by Django 5.0.3 on 2024-03-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('full_name_student', models.TextField(max_length=100)),
                ('mom_name', models.TextField(max_length=100)),
                ('father_name', models.TextField(max_length=100)),
                ('mom_contact', models.TextField(max_length=20)),
                ('father_contact', models.TextField(max_length=20)),
                ('mom_email', models.TextField(max_length=30)),
                ('father_email', models.TextField(max_length=30)),
                ('address', models.TextField(max_length=50)),
                ('classes', models.TextField(max_length=3)),
            ],
        ),
    ]
