# Generated by Django 5.0.3 on 2024-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='father_email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='mom_email',
            field=models.EmailField(max_length=30),
        ),
    ]
